services:
  db:
    image: postgres:17.6
    container_name: postgres-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - backend
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - '${POSTGRES_PORT}:5432'

volumes:
  db-data:

networks:
  backend:
    driver: bridge